CREATE TABLE "Recursos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Descripcion" character varying(500),
    "Categoria" character varying(50) NOT NULL,
    "Cantidad" integer NOT NULL,
    "CantidadDisponible" integer NOT NULL,
    "Unidad" character varying(50),
    "Ubicacion" character varying(200),
    "ValorEstimado" numeric(10,2),
    "Notas" character varying(1000),
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Recursos" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(50) NOT NULL,
    "Descripcion" character varying(200) NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PrimerNombre" character varying(100) NOT NULL,
    "Apellido" character varying(100) NOT NULL,
    "CorreoElectronico" character varying(255) NOT NULL,
    "NombreDeUsuario" character varying(50) NOT NULL,
    "HashDeContrasena" text NOT NULL,
    "IdRol" integer NOT NULL,
    "FechaDeNacimiento" timestamp with time zone,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Roles_IdRol" FOREIGN KEY ("IdRol") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Actividades" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(200) NOT NULL,
    "AreaDeEnfoque" character varying(100) NOT NULL,
    "DescripcionDetallada" character varying(2000),
    "DuracionEstimadaMinutos" integer NOT NULL,
    "MaterialesNecesarios" character varying(1000),
    "FechaDelEvento" timestamp with time zone NOT NULL,
    "CreadoPorIdUsuario" integer NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Actividades" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Actividades_Usuarios_CreadoPorIdUsuario" FOREIGN KEY ("CreadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ActividadesMontessori" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(300) NOT NULL,
    "AreaPedagogica" character varying(100) NOT NULL,
    "FechaActividad" timestamp with time zone NOT NULL,
    "HoraActividad" interval,
    "EdadMinima" numeric(3,1) NOT NULL,
    "EdadMaxima" numeric(3,1) NOT NULL,
    "DuracionMinutos" integer NOT NULL,
    "ObjetivoEspecifico" character varying(1000) NOT NULL,
    "MaterialesNecesarios" character varying(2000) NOT NULL,
    "MontajeAmbiente" character varying(2000) NOT NULL,
    "Prerequisitos" character varying(1000),
    "PresentacionPasoAPaso" character varying(5000) NOT NULL,
    "ControlDelError" character varying(2000) NOT NULL,
    "AspectosAutonomia" character varying(1000),
    "LimitesYNormas" character varying(1000),
    "IndicadoresDeLogro" character varying(2000) NOT NULL,
    "AdaptacionesVariaciones" character varying(2000),
    "NivelDificultad" character varying(50),
    "EvidenciaUrl" character varying(500),
    "ObservacionesAdicionales" character varying(3000),
    "ChecklistMontessori" character varying(1000),
    "CreadoPorIdUsuario" integer NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_ActividadesMontessori" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActividadesMontessori_Usuarios_CreadoPorIdUsuario" FOREIGN KEY ("CreadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AsignacionesDeRecurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdRecurso" integer NOT NULL,
    "IdVoluntario" integer NOT NULL,
    "CantidadAsignada" integer NOT NULL,
    "Estado" integer NOT NULL,
    "AsignadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ConfirmadoEn" timestamp with time zone,
    "IniciadoEn" timestamp with time zone,
    "DevueltoEn" timestamp with time zone,
    "FechaEsperadaDeDevolucion" timestamp with time zone,
    "NotasIniciales" character varying(1000),
    "NotasDelVoluntario" character varying(1000),
    "AsignadoPorIdUsuario" integer,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_AsignacionesDeRecurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AsignacionesDeRecurso_Recursos_IdRecurso" FOREIGN KEY ("IdRecurso") REFERENCES "Recursos" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AsignacionesDeRecurso_Usuarios_AsignadoPorIdUsuario" FOREIGN KEY ("AsignadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AsignacionesDeRecurso_Usuarios_IdVoluntario" FOREIGN KEY ("IdVoluntario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Devocionales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(200) NOT NULL,
    "FechaProgramada" date,
    "VoluntarioAsignadoId" integer,
    "VoluntarioAsignado" character varying(100),
    "Pasaje" character varying(200),
    "TextoClave" character varying(1000),
    "Objetivo" character varying(1000),
    "Idea" character varying(1000),
    "PuntosPrincipales" text,
    "Aplicacion" character varying(2000),
    "Reto" character varying(1000),
    "Oracion" character varying(1000),
    "Recursos" character varying(2000),
    "Estado" integer NOT NULL DEFAULT 0,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "CreadoPorIdUsuario" integer NOT NULL,
    "ActualizadoPorIdUsuario" integer,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Devocionales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Devocionales_Usuarios_ActualizadoPorIdUsuario" FOREIGN KEY ("ActualizadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Devocionales_Usuarios_CreadoPorIdUsuario" FOREIGN KEY ("CreadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Devocionales_Usuarios_VoluntarioAsignadoId" FOREIGN KEY ("VoluntarioAsignadoId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Niveles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Descripcion" character varying(500),
    "EdadMinima" numeric(3,1) NOT NULL,
    "EdadMaxima" numeric(3,1) NOT NULL,
    "IdVoluntario" integer,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Niveles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Niveles_Usuarios_IdVoluntario" FOREIGN KEY ("IdVoluntario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "PerfilesUsuario" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdUsuario" integer NOT NULL,
    "FotoPerfil" character varying(500),
    "Telefono" character varying(20),
    "Direccion" character varying(200),
    "Ciudad" character varying(100),
    "Pais" character varying(50),
    "ContactoEmergenciaNombre" character varying(100),
    "ContactoEmergenciaTelefono" character varying(20),
    "ContactoEmergenciaRelacion" character varying(50),
    "NombrePadre" character varying(100),
    "NombreMadre" character varying(100),
    "NombreTutor" character varying(100),
    "Alergias" character varying(500),
    "CondicionesMedicas" character varying(500),
    "Medicamentos" character varying(500),
    "Biografia" character varying(1000),
    "Intereses" character varying(500),
    "Facebook" character varying(100),
    "Instagram" character varying(100),
    "Twitter" character varying(100),
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_PerfilesUsuario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PerfilesUsuario_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Tareas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" character varying(200) NOT NULL,
    "Descripcion" character varying(2000),
    "FechaInicio" timestamp with time zone,
    "FechaFin" timestamp with time zone,
    "CreadoPorIdUsuario" integer NOT NULL,
    "Estado" integer NOT NULL DEFAULT 0,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    "NotasCoordinador" character varying(1000),
    "NotasVoluntario" character varying(1000),
    "FechaRevision" timestamp with time zone,
    "RazonRechazo" character varying(500),
    CONSTRAINT "PK_Tareas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tareas_Usuarios_CreadoPorIdUsuario" FOREIGN KEY ("CreadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AsignacionesDeActividad" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ActividadId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    "AsignadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_AsignacionesDeActividad" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AsignacionesDeActividad_Actividades_ActividadId" FOREIGN KEY ("ActividadId") REFERENCES "Actividades" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AsignacionesDeActividad_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "LogrosMontessori" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(200) NOT NULL,
    "Descripcion" character varying(500) NOT NULL,
    "Icono" character varying(50) NOT NULL,
    "EsObtenido" boolean NOT NULL DEFAULT FALSE,
    "FechaObtencion" timestamp with time zone,
    "ActividadMontessoriId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_LogrosMontessori" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogrosMontessori_ActividadesMontessori_ActividadMontessoriId" FOREIGN KEY ("ActividadMontessoriId") REFERENCES "ActividadesMontessori" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LogrosMontessori_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RegistrosDeUsoDeRecurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdAsignacionDeRecurso" integer NOT NULL,
    "TipoDeEvento" integer NOT NULL,
    "Titulo" character varying(200) NOT NULL,
    "Descripcion" character varying(2000) NOT NULL,
    "CondicionAntes" integer,
    "CondicionDespues" integer,
    "CantidadAfectada" integer,
    "AccionesTomadas" character varying(1000),
    "Recomendaciones" character varying(1000),
    "RequiereSeguimiento" boolean NOT NULL,
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ReportadoPorIdUsuario" integer NOT NULL,
    "UrlsDeFotos" character varying(500),
    "EstaResuelto" boolean NOT NULL,
    "ResueltoEn" timestamp with time zone,
    "ResueltoPorIdUsuario" integer,
    "NotasDeResolucion" character varying(1000),
    CONSTRAINT "PK_RegistrosDeUsoDeRecurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegistrosDeUsoDeRecurso_AsignacionesDeRecurso_IdAsignacionD~" FOREIGN KEY ("IdAsignacionDeRecurso") REFERENCES "AsignacionesDeRecurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RegistrosDeUsoDeRecurso_Usuarios_ReportadoPorIdUsuario" FOREIGN KEY ("ReportadoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RegistrosDeUsoDeRecurso_Usuarios_ResueltoPorIdUsuario" FOREIGN KEY ("ResueltoPorIdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Asistencias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdNivel" integer NOT NULL,
    "IdUsuario" integer NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "Presente" boolean NOT NULL,
    "Observaciones" character varying(500),
    "CreadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ActualizadoEn" timestamp with time zone,
    "EstaEliminado" boolean NOT NULL,
    CONSTRAINT "PK_Asistencias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Asistencias_Niveles_IdNivel" FOREIGN KEY ("IdNivel") REFERENCES "Niveles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Asistencias_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "NivelesDeParticipantes" (
    "IdNivel" integer NOT NULL,
    "IdUsuario" integer NOT NULL,
    "AsignadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_NivelesDeParticipantes" PRIMARY KEY ("IdNivel", "IdUsuario"),
    CONSTRAINT "FK_NivelesDeParticipantes_Niveles_IdNivel" FOREIGN KEY ("IdNivel") REFERENCES "Niveles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NivelesDeParticipantes_Usuarios_IdUsuario" FOREIGN KEY ("IdUsuario") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AsignacionesDeTarea" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TareaId" integer NOT NULL,
    "UsuarioId" integer NOT NULL,
    "EstadoVoluntario" integer NOT NULL DEFAULT 0,
    "AsignadoEn" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "VistaEn" timestamp with time zone,
    "IniciadaEn" timestamp with time zone,
    "CompletadaEn" timestamp with time zone,
    "EstaActivo" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_AsignacionesDeTarea" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AsignacionesDeTarea_Tareas_TareaId" FOREIGN KEY ("TareaId") REFERENCES "Tareas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AsignacionesDeTarea_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);


INSERT INTO "Roles" ("Id", "CreadoEn", "Descripcion", "EstaActivo", "Nombre")
VALUES (1, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Full system access', TRUE, 'Administrator');
INSERT INTO "Roles" ("Id", "CreadoEn", "Descripcion", "EstaActivo", "Nombre")
VALUES (2, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Acceso de participante / beneficiario', TRUE, 'Participante');
INSERT INTO "Roles" ("Id", "CreadoEn", "Descripcion", "EstaActivo", "Nombre")
VALUES (3, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Read-only access', TRUE, 'Viewer');
INSERT INTO "Roles" ("Id", "CreadoEn", "Descripcion", "EstaActivo", "Nombre")
VALUES (4, TIMESTAMPTZ '2024-01-15T00:00:00Z', 'Management access', TRUE, 'Manager');
INSERT INTO "Roles" ("Id", "CreadoEn", "Descripcion", "EstaActivo", "Nombre")
VALUES (5, TIMESTAMPTZ '2024-02-01T00:00:00Z', 'Coordinación y supervisión', TRUE, 'Coordinador');


INSERT INTO "Usuarios" ("Id", "ActualizadoEn", "Apellido", "CorreoElectronico", "CreadoEn", "EstaActivo", "FechaDeNacimiento", "HashDeContrasena", "IdRol", "NombreDeUsuario", "PrimerNombre")
VALUES (1, NULL, 'System', 'admin@apipg.com', TIMESTAMPTZ '2024-01-01T00:00:00Z', TRUE, NULL, 'b/7s5TnSLbUEMwpw1dfZFqDzDuwr/6CKBhTF4K+K5KQ=', 1, 'admin', 'Admin');
INSERT INTO "Usuarios" ("Id", "ActualizadoEn", "Apellido", "CorreoElectronico", "CreadoEn", "EstaActivo", "FechaDeNacimiento", "HashDeContrasena", "IdRol", "NombreDeUsuario", "PrimerNombre")
VALUES (2, NULL, 'Pérez', 'juan.perez@email.com', TIMESTAMPTZ '2024-01-15T00:00:00Z', TRUE, NULL, '5koThLVJCEZ3mjd4R2huzmFy7+Otmfgvnes9PHPaN0U=', 2, 'jperez', 'Juan');
INSERT INTO "Usuarios" ("Id", "ActualizadoEn", "Apellido", "CorreoElectronico", "CreadoEn", "EstaActivo", "FechaDeNacimiento", "HashDeContrasena", "IdRol", "NombreDeUsuario", "PrimerNombre")
VALUES (3, NULL, 'García', 'maria.garcia@email.com', TIMESTAMPTZ '2024-01-20T00:00:00Z', TRUE, NULL, '5koThLVJCEZ3mjd4R2huzmFy7+Otmfgvnes9PHPaN0U=', 3, 'mgarcia', 'María');
INSERT INTO "Usuarios" ("Id", "ActualizadoEn", "Apellido", "CorreoElectronico", "CreadoEn", "EstaActivo", "FechaDeNacimiento", "HashDeContrasena", "IdRol", "NombreDeUsuario", "PrimerNombre")
VALUES (4, NULL, 'Coordinador', 'coordinador@apipg.com', TIMESTAMPTZ '2024-01-25T00:00:00Z', TRUE, NULL, 'QSNk6NjkEQY5MPIFVC9cEVVPerlnGk2oA7V5puh9dew=', 5, 'coordinador', 'Carlos');


CREATE INDEX "IX_Actividades_AreaDeEnfoque" ON "Actividades" ("AreaDeEnfoque");


CREATE INDEX "IX_Actividades_CreadoEn" ON "Actividades" ("CreadoEn");


CREATE INDEX "IX_Actividades_CreadoPorIdUsuario" ON "Actividades" ("CreadoPorIdUsuario");


CREATE INDEX "IX_Actividades_EstaActivo" ON "Actividades" ("EstaActivo");


CREATE INDEX "IX_Actividades_FechaDelEvento" ON "Actividades" ("FechaDelEvento");


CREATE INDEX "IX_Actividades_Titulo" ON "Actividades" ("Titulo");


CREATE INDEX "IX_ActividadesMontessori_AreaPedagogica" ON "ActividadesMontessori" ("AreaPedagogica");


CREATE INDEX "IX_ActividadesMontessori_CreadoPorIdUsuario" ON "ActividadesMontessori" ("CreadoPorIdUsuario");


CREATE INDEX "IX_ActividadesMontessori_EstaActivo" ON "ActividadesMontessori" ("EstaActivo");


CREATE INDEX "IX_ActividadesMontessori_FechaActividad" ON "ActividadesMontessori" ("FechaActividad");


CREATE INDEX "IX_ActividadesMontessori_Nombre" ON "ActividadesMontessori" ("Nombre");


CREATE INDEX "IX_AsignacionesDeActividad_ActividadId" ON "AsignacionesDeActividad" ("ActividadId");


CREATE UNIQUE INDEX "IX_AsignacionesDeActividad_ActividadId_UsuarioId" ON "AsignacionesDeActividad" ("ActividadId", "UsuarioId");


CREATE INDEX "IX_AsignacionesDeActividad_AsignadoEn" ON "AsignacionesDeActividad" ("AsignadoEn");


CREATE INDEX "IX_AsignacionesDeActividad_UsuarioId" ON "AsignacionesDeActividad" ("UsuarioId");


CREATE INDEX "IX_AsignacionesDeRecurso_AsignadoEn" ON "AsignacionesDeRecurso" ("AsignadoEn");


CREATE INDEX "IX_AsignacionesDeRecurso_AsignadoPorIdUsuario" ON "AsignacionesDeRecurso" ("AsignadoPorIdUsuario");


CREATE INDEX "IX_AsignacionesDeRecurso_Estado" ON "AsignacionesDeRecurso" ("Estado");


CREATE INDEX "IX_AsignacionesDeRecurso_IdRecurso" ON "AsignacionesDeRecurso" ("IdRecurso");


CREATE INDEX "IX_AsignacionesDeRecurso_IdVoluntario" ON "AsignacionesDeRecurso" ("IdVoluntario");


CREATE INDEX "IX_AsignacionesDeTarea_AsignadoEn" ON "AsignacionesDeTarea" ("AsignadoEn");


CREATE INDEX "IX_AsignacionesDeTarea_EstadoVoluntario" ON "AsignacionesDeTarea" ("EstadoVoluntario");


CREATE INDEX "IX_AsignacionesDeTarea_TareaId" ON "AsignacionesDeTarea" ("TareaId");


CREATE UNIQUE INDEX "IX_AsignacionesDeTarea_TareaId_UsuarioId" ON "AsignacionesDeTarea" ("TareaId", "UsuarioId");


CREATE INDEX "IX_AsignacionesDeTarea_UsuarioId" ON "AsignacionesDeTarea" ("UsuarioId");


CREATE INDEX "IX_Asistencias_IdNivel" ON "Asistencias" ("IdNivel");


CREATE INDEX "IX_Asistencias_IdUsuario" ON "Asistencias" ("IdUsuario");


CREATE INDEX "IX_Devocionales_ActualizadoPorIdUsuario" ON "Devocionales" ("ActualizadoPorIdUsuario");


CREATE INDEX "IX_Devocionales_CreadoEn" ON "Devocionales" ("CreadoEn");


CREATE INDEX "IX_Devocionales_CreadoPorIdUsuario" ON "Devocionales" ("CreadoPorIdUsuario");


CREATE INDEX "IX_Devocionales_EstaActivo" ON "Devocionales" ("EstaActivo");


CREATE INDEX "IX_Devocionales_Estado" ON "Devocionales" ("Estado");


CREATE INDEX "IX_Devocionales_FechaProgramada" ON "Devocionales" ("FechaProgramada");


CREATE INDEX "IX_Devocionales_Titulo" ON "Devocionales" ("Titulo");


CREATE INDEX "IX_Devocionales_VoluntarioAsignadoId" ON "Devocionales" ("VoluntarioAsignadoId");


CREATE INDEX "IX_LogrosMontessori_ActividadMontessoriId" ON "LogrosMontessori" ("ActividadMontessoriId");


CREATE INDEX "IX_LogrosMontessori_EsObtenido" ON "LogrosMontessori" ("EsObtenido");


CREATE INDEX "IX_LogrosMontessori_FechaObtencion" ON "LogrosMontessori" ("FechaObtencion");


CREATE INDEX "IX_LogrosMontessori_UsuarioId" ON "LogrosMontessori" ("UsuarioId");


CREATE INDEX "IX_Niveles_EdadMaxima" ON "Niveles" ("EdadMaxima");


CREATE INDEX "IX_Niveles_EdadMinima" ON "Niveles" ("EdadMinima");


CREATE INDEX "IX_Niveles_IdVoluntario" ON "Niveles" ("IdVoluntario");


CREATE INDEX "IX_NivelesDeParticipantes_IdUsuario" ON "NivelesDeParticipantes" ("IdUsuario");


CREATE INDEX "IX_PerfilesUsuario_Ciudad" ON "PerfilesUsuario" ("Ciudad");


CREATE UNIQUE INDEX "IX_PerfilesUsuario_IdUsuario" ON "PerfilesUsuario" ("IdUsuario");


CREATE INDEX "IX_PerfilesUsuario_Telefono" ON "PerfilesUsuario" ("Telefono");


CREATE INDEX "IX_Recursos_Categoria" ON "Recursos" ("Categoria");


CREATE INDEX "IX_Recursos_EstaActivo" ON "Recursos" ("EstaActivo");


CREATE INDEX "IX_Recursos_Nombre" ON "Recursos" ("Nombre");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_CreadoEn" ON "RegistrosDeUsoDeRecurso" ("CreadoEn");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_EstaResuelto" ON "RegistrosDeUsoDeRecurso" ("EstaResuelto");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_IdAsignacionDeRecurso" ON "RegistrosDeUsoDeRecurso" ("IdAsignacionDeRecurso");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_ReportadoPorIdUsuario" ON "RegistrosDeUsoDeRecurso" ("ReportadoPorIdUsuario");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_ResueltoPorIdUsuario" ON "RegistrosDeUsoDeRecurso" ("ResueltoPorIdUsuario");


CREATE INDEX "IX_RegistrosDeUsoDeRecurso_TipoDeEvento" ON "RegistrosDeUsoDeRecurso" ("TipoDeEvento");


CREATE UNIQUE INDEX "IX_Roles_Nombre" ON "Roles" ("Nombre");


CREATE INDEX "IX_Tareas_CreadoEn" ON "Tareas" ("CreadoEn");


CREATE INDEX "IX_Tareas_CreadoPorIdUsuario" ON "Tareas" ("CreadoPorIdUsuario");


CREATE INDEX "IX_Tareas_EstaActivo" ON "Tareas" ("EstaActivo");


CREATE INDEX "IX_Tareas_Estado" ON "Tareas" ("Estado");


CREATE INDEX "IX_Tareas_FechaFin" ON "Tareas" ("FechaFin");


CREATE INDEX "IX_Tareas_FechaInicio" ON "Tareas" ("FechaInicio");


CREATE INDEX "IX_Tareas_Titulo" ON "Tareas" ("Titulo");


CREATE UNIQUE INDEX "IX_Usuarios_CorreoElectronico" ON "Usuarios" ("CorreoElectronico");


CREATE INDEX "IX_Usuarios_IdRol" ON "Usuarios" ("IdRol");


CREATE UNIQUE INDEX "IX_Usuarios_NombreDeUsuario" ON "Usuarios" ("NombreDeUsuario");


SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Usuarios"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Usuarios") + 1,
        nextval(pg_get_serial_sequence('"Usuarios"', 'Id'))),
    false);


