// <auto-generated />
using System;
using ApiPG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiPG.Migrations
{
    [DbContext(typeof(ApiPGContext))]
    [Migration("20251026031532_AgregarSistemaDeActividades")]
    partial class AgregarSistemaDeActividades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiPG.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AreaDeEnfoque")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionDetallada")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaDelEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialesNecesarios")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaDeEnfoque");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("CreadoPorIdUsuario");

                    b.HasIndex("EstaActivo");

                    b.HasIndex("FechaDelEvento");

                    b.HasIndex("Titulo");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AsignadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("AsignadoEn");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ActividadId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AsignacionesDeActividad", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AsignadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("AsignadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadAsignada")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DevueltoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEsperadaDeDevolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("integer");

                    b.Property<int>("IdVoluntario")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IniciadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasDelVoluntario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotasIniciales")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoEn");

                    b.HasIndex("AsignadoPorIdUsuario");

                    b.HasIndex("Estado");

                    b.HasIndex("IdRecurso");

                    b.HasIndex("IdVoluntario");

                    b.ToTable("AsignacionesDeRecurso", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AsignadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("CompletadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("EstadoVoluntario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("IniciadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TareaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VistaEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoEn");

                    b.HasIndex("EstadoVoluntario");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TareaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AsignacionesDeTarea", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstaEliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdNivel")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Asistencias", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Devocional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ActualizadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Aplicacion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<string>("Idea")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Oracion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Pasaje")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PuntosPrincipales")
                        .HasColumnType("text");

                    b.Property<string>("Recursos")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TextoClave")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VoluntarioAsignado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VoluntarioAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActualizadoPorIdUsuario");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("CreadoPorIdUsuario");

                    b.HasIndex("EstaActivo");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("Titulo");

                    b.HasIndex("VoluntarioAsignadoId");

                    b.ToTable("Devocionales", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("IdVoluntario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdVoluntario");

                    b.ToTable("Niveles", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.NivelDeParticipante", b =>
                {
                    b.Property<int>("IdNivel")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AsignadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("IdNivel", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("NivelesDeParticipantes", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("EstaActivo");

                    b.HasIndex("Nombre");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.RegistroDeUsoDeRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionesTomadas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("CantidadAfectada")
                        .HasColumnType("integer");

                    b.Property<int?>("CondicionAntes")
                        .HasColumnType("integer");

                    b.Property<int?>("CondicionDespues")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EstaResuelto")
                        .HasColumnType("boolean");

                    b.Property<int>("IdAsignacionDeRecurso")
                        .HasColumnType("integer");

                    b.Property<string>("NotasDeResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReportadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereSeguimiento")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResueltoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResueltoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDeEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UrlsDeFotos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("EstaResuelto");

                    b.HasIndex("IdAsignacionDeRecurso");

                    b.HasIndex("ReportadoPorIdUsuario");

                    b.HasIndex("ResueltoPorIdUsuario");

                    b.HasIndex("TipoDeEvento");

                    b.ToTable("RegistrosDeUsoDeRecurso", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Full system access",
                            EstaActivo = true,
                            Nombre = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Acceso de participante / beneficiario",
                            EstaActivo = true,
                            Nombre = "Participante"
                        },
                        new
                        {
                            Id = 3,
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Read-only access",
                            EstaActivo = true,
                            Nombre = "Viewer"
                        },
                        new
                        {
                            Id = 4,
                            CreadoEn = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Management access",
                            EstaActivo = true,
                            Nombre = "Manager"
                        },
                        new
                        {
                            Id = 5,
                            CreadoEn = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Coordinación y supervisión",
                            EstaActivo = true,
                            Nombre = "Coordinador"
                        });
                });

            modelBuilder.Entity("ApiPG.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreadoPorIdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotasCoordinador")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotasVoluntario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RazonRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoEn");

                    b.HasIndex("CreadoPorIdUsuario");

                    b.HasIndex("EstaActivo");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("Titulo");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("ApiPG.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaDeNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreDeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "System",
                            CorreoElectronico = "admin@apipg.com",
                            CreadoEn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstaActivo = true,
                            HashDeContrasena = "b/7s5TnSLbUEMwpw1dfZFqDzDuwr/6CKBhTF4K+K5KQ=",
                            IdRol = 1,
                            NombreDeUsuario = "admin",
                            PrimerNombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Pérez",
                            CorreoElectronico = "juan.perez@email.com",
                            CreadoEn = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstaActivo = true,
                            HashDeContrasena = "5koThLVJCEZ3mjd4R2huzmFy7+Otmfgvnes9PHPaN0U=",
                            IdRol = 2,
                            NombreDeUsuario = "jperez",
                            PrimerNombre = "Juan"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "García",
                            CorreoElectronico = "maria.garcia@email.com",
                            CreadoEn = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstaActivo = true,
                            HashDeContrasena = "5koThLVJCEZ3mjd4R2huzmFy7+Otmfgvnes9PHPaN0U=",
                            IdRol = 3,
                            NombreDeUsuario = "mgarcia",
                            PrimerNombre = "María"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Coordinador",
                            CorreoElectronico = "coordinador@apipg.com",
                            CreadoEn = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstaActivo = true,
                            HashDeContrasena = "QSNk6NjkEQY5MPIFVC9cEVVPerlnGk2oA7V5puh9dew=",
                            IdRol = 5,
                            NombreDeUsuario = "coordinador",
                            PrimerNombre = "Carlos"
                        });
                });

            modelBuilder.Entity("ApiPG.Models.Actividad", b =>
                {
                    b.HasOne("ApiPG.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeActividad", b =>
                {
                    b.HasOne("ApiPG.Models.Actividad", "Actividad")
                        .WithMany("AsignacionesDeActividad")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeRecurso", b =>
                {
                    b.HasOne("ApiPG.Models.Usuario", "AsignadoPor")
                        .WithMany()
                        .HasForeignKey("AsignadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiPG.Models.Recurso", "Recurso")
                        .WithMany("AsignacionesDeRecurso")
                        .HasForeignKey("IdRecurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "Voluntario")
                        .WithMany()
                        .HasForeignKey("IdVoluntario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoPor");

                    b.Navigation("Recurso");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeTarea", b =>
                {
                    b.HasOne("ApiPG.Models.Tarea", "Tarea")
                        .WithMany("AsignacionesDeTarea")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPG.Models.Asistencia", b =>
                {
                    b.HasOne("ApiPG.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPG.Models.Devocional", b =>
                {
                    b.HasOne("ApiPG.Models.Usuario", "ActualizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ActualizadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiPG.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "VoluntarioAsignadoUser")
                        .WithMany()
                        .HasForeignKey("VoluntarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualizadoPorUsuario");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("VoluntarioAsignadoUser");
                });

            modelBuilder.Entity("ApiPG.Models.Nivel", b =>
                {
                    b.HasOne("ApiPG.Models.Usuario", "Voluntario")
                        .WithMany()
                        .HasForeignKey("IdVoluntario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("ApiPG.Models.NivelDeParticipante", b =>
                {
                    b.HasOne("ApiPG.Models.Nivel", "Nivel")
                        .WithMany("ParticipantesDelNivel")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nivel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPG.Models.RegistroDeUsoDeRecurso", b =>
                {
                    b.HasOne("ApiPG.Models.AsignacionDeRecurso", "AsignacionDeRecurso")
                        .WithMany("RegistrosDeUso")
                        .HasForeignKey("IdAsignacionDeRecurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "ReportadoPor")
                        .WithMany()
                        .HasForeignKey("ReportadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPG.Models.Usuario", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsignacionDeRecurso");

                    b.Navigation("ReportadoPor");

                    b.Navigation("ResueltoPor");
                });

            modelBuilder.Entity("ApiPG.Models.Tarea", b =>
                {
                    b.HasOne("ApiPG.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("ApiPG.Models.Usuario", b =>
                {
                    b.HasOne("ApiPG.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApiPG.Models.Actividad", b =>
                {
                    b.Navigation("AsignacionesDeActividad");
                });

            modelBuilder.Entity("ApiPG.Models.AsignacionDeRecurso", b =>
                {
                    b.Navigation("RegistrosDeUso");
                });

            modelBuilder.Entity("ApiPG.Models.Nivel", b =>
                {
                    b.Navigation("ParticipantesDelNivel");
                });

            modelBuilder.Entity("ApiPG.Models.Recurso", b =>
                {
                    b.Navigation("AsignacionesDeRecurso");
                });

            modelBuilder.Entity("ApiPG.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiPG.Models.Tarea", b =>
                {
                    b.Navigation("AsignacionesDeTarea");
                });
#pragma warning restore 612, 618
        }
    }
}
